#define NAME divide_error_handler
#include "handlers/handler.def"

#define NAME debug_handler
#include "handlers/handler.def"

#define NAME breakpoint_handler
#include "handlers/handler.def"

#define NAME overflow_handler
#include "handlers/handler.def"

#define NAME bound_range_exceeded_handler
#include "handlers/handler.def"

#define NAME invalid_opcode_handler
#include "handlers/handler.def"

#define NAME device_not_available_handler
#include "handlers/handler.def"

#define NAME double_fault_handler
#include "handlers/handler.def"

#define NAME invalid_tss_handler
#include "handlers/handler.def"

#define NAME segment_not_present_handler
#include "handlers/handler.def"

#define NAME stack_segment_fault_handler
#include "handlers/handler.def"

#define NAME general_protection_handler
#include "handlers/handler.def"

#define NAME page_fault_handler
#include "handlers/handler.def"

#define NAME alignment_check_handler
#include "handlers/handler.def"

#define NAME machine_check_handler
#include "handlers/handler.def"

#define NAME syscall_handler
#include "handlers/handler.def"

#define NAME fork_handler
#include "handlers/handler.def"

#define NAME exec_handler
#include "handlers/handler.def"

#define NAME wait_handler
#include "handlers/handler.def"

#define NAME deschedule_handler
#include "handlers/handler.def"

#define NAME make_runnable_handler
#include "handlers/handler.def"

#define NAME gettid_handler
#include "handlers/handler.def"

#define NAME new_pages_handler
#include "handlers/handler.def"

#define NAME remove_pages_handler
#include "handlers/handler.def"

#define NAME sleep_handler
#include "handlers/handler.def"

#define NAME getchar_handler
#include "handlers/handler.def"

#define NAME readline_handler
#include "handlers/handler.def"

#define NAME print_handler
#include "handlers/handler.def"

#define NAME set_term_color_handler
#include "handlers/handler.def"

#define NAME set_cursor_pos_handler
#include "handlers/handler.def"

#define NAME get_cursor_pos_handler
#include "handlers/handler.def"

#define NAME thread_fork_handler
#include "handlers/handler.def"

#define NAME get_ticks_handler
#include "handlers/handler.def"

#define NAME misbehave_handler
#include "handlers/handler.def"

#define NAME halt_handler
#include "handlers/handler.def"

#define NAME ls_handler
#include "handlers/handler.def"

#define NAME task_vanish_handler
#include "handlers/handler.def"

#define NAME set_status_handler
#include "handlers/handler.def"

#define NAME vanish_handler
#include "handlers/handler.def"

#define NAME timer_handler
#include "handlers/handler.def"

#define NAME keyboard_handler
#include "handlers/handler.def"

