/** 
* @file reg.h
* @brief This one is cool. 
* 
* On entry to one of our handlers, a regstate_t describes 
*  the physical contents of the stack, so we can mutate user 
*  state as part of the regstate struct. 
*
*  They are also convenient definitions for setting up the context
*   for a fork. 
*
* @author Justin Scheiner
* @author Tim Wilson
* @date 2010-11-12
*/

#ifndef REG_X239SB19
#define REG_X239SB19

typedef struct PUSHA
{
   long edi;         
   long esi;
   long ebp;
   long original_esp;
   long ebx;
   long edx;
   long ecx;
   long eax;
} pusha_t;

/** 
* @brief  Image of the register state on entry to an interrupt handler
*  when an error is not generated. 
*/
typedef struct REGSTATE
{ 
   /* Generated by pusha: */
   pusha_t pusha;
   
   /* Generated by INT */
   long eip;
   long cs;
   long eflags;
   long esp;
   long ss;
} regstate_t;

/** 
* @brief The argument for the given syscall - either the value itself, 
*  or the address of a "packet" containing the arguments in user space.
* 
* @param regstate The register state on entry to a system call.
* 
* @return The argument.
*/
#define SYSCALL_ARG(regstate) \
   (regstate->esi)

/**
 * @brief Return with the given value. Useful for trap handlers to set the eax
 * return value.
 *
 *  Requires the argument to the handler be declared "reg" 
 *
 * @param ret The value to return.
 */
#define RETURN(reg, ret) \
   do { \
      reg->eax = (ret); \
      return; \
   } while (0)

#endif /* end of include guard: REG_X239SB19 */


