
#ifndef REG_X239SB19
#define REG_X239SB19

#include <stdint.h>

typedef struct PUSHA
{
   uint32_t edi;         
   uint32_t esi;
   uint32_t ebp;
   uint32_t original_esp;
   uint32_t ebx;
   uint32_t edx;
   uint32_t ecx;
   uint32_t eax;
} pusha_t;

/** 
* @brief  Image of the register state on entry to an interrupt handler
*  when an error is generated. 
*/
typedef struct REGSTATE_ERROR
{ 
   /* Generated by pusha: */
   pusha_t pusha;

   /* Generated by INT: */
   uint32_t ecode;
   uint32_t eip;
   uint32_t cs;
   uint32_t eflags;
   uint32_t esp;
   uint32_t ss;
} regstate_error_t;

/** 
* @brief  Image of the register state on entry to an interrupt handler
*  when an error is not generated. 
*/
typedef struct REGSTATE
{ 
   /* Generated by pusha: */
   pusha_t pusha;
   
   /* Generated by INT */
   uint32_t eip;
   uint32_t cs;
   uint32_t eflags;
   uint32_t esp;
   uint32_t ss;
} regstate_t;

/** 
* @brief The argument for the given syscall - either the value itself, 
*  or the address of a "packet" containing the arguments in user space.
* 
* @param regstate The register state on entry to a system call.
* 
* @return The argument.
*/
#define SYSCALL_ARG(regstate) \
	((regstate).pusha.esi)

/**
 * @brief Return with the given value. Useful for trap handlers to set the eax
 * return value.
 *
 * @param ret The value to return.
 */
#define RETURN(ret) \
	do { \
		reg.pusha.eax = ret; \
		return; \
	} while (0)

#endif /* end of include guard: REG_X239SB19 */


